working on release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -12,13 +12,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Verify latest ci completed successfully
-        run: |
-          apt-get install -y jq
-          STATUS=$(curl https://_:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/ReallyLiri/kubescout/actions/workflows/ci.yaml/runs |  jq -r '.workflow_runs[0].status')
-          if [ "$STATUS" != "completed" ]; then
-            echo "latest ci run is in status $STATUS, cannot create a release"
-            exit 1
-          fi
+        uses: docker://dwdraju/alpine-curl-jq
+        with:
+          entrypoint: bash
+          args: |
+            apt-get install -y jq
+            STATUS=$(curl https://_:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/ReallyLiri/kubescout/actions/workflows/ci.yaml/runs |  jq -r '.workflow_runs[0].status')
+            if [ "$STATUS" != "completed" ]; then
+              echo "latest ci run is in status $STATUS, cannot create a release"
+              exit 1
+            fi
 
       - name: Extract tag name
         id: tag
